services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: perktree
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  frontend:
    image: perktree-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8019:80"

  backend:
    image: perktree-backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_ENV: prod
      DJANGO_DEBUG: 'true'
      DJANGO_ADMIN_USER: ${DJANGO_ADMIN_USER}
      DJANGO_ADMIN_MAIL: ${DJANGO_ADMIN_MAIL}
      DJANGO_ADMIN_PASS: ${DJANGO_ADMIN_PASS}
      APP_HOST: perktree.theedgeofrage.com
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: perktree
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      PERKS_DIR: /app/static/perks

volumes:
  db:
