version: "3"
services:
  db:
    image: mariadb
    container_name: perktree-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: perktree
    volumes:
      - /mnt/perktree/db:/var/lib/mysql

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: perktree-frontend
    restart: unless-stopped
    ports:
      - 8019:80
    links:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: perktree-backend
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_ENV: prod
      DJANGO_DEBUG: True
      DJANGO_ADMIN_USER: ${DJANGO_ADMIN_USER}
      DJANGO_ADMIN_MAIL: ${DJANGO_ADMIN_MAIL}
      DJANGO_ADMIN_PASS: ${DJANGO_ADMIN_PASS}
      APP_HOST: perktree.theedgeofrage.com
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: perktree
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      PERKS_DIR: /app/static/perks
    links:
      - db

