# vim: set ft=dockerfile :
FROM python:3-alpine

COPY backend /app
COPY parser /app/parser
WORKDIR /app
EXPOSE 80

RUN set -ex \
	&& apk add --no-cache --virtual .build-deps \
		gcc \
		make \
		libc-dev \
		musl-dev \
		libffi-dev \
		mariadb-dev \
	&& apk add --no-cache mariadb-connector-c \
	&& pip install --no-cache-dir pipenv \
	&& pipenv install --system --clear \
	&& apk del .build-deps \
	&& rm db.sqlite3

CMD ["./entrypoint.sh"]

