version: "3"
services:
  db:
    image: postgres:alpine
    container_name: perktree-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: perktree
    volumes:
      - /mnt/perktree/db:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: perktree-frontend
    restart: unless-stopped
    ports:
      - ::1:8019:80
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: perktree-backend
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_ENV: prod
      DJANGO_DEBUG: 'true'
      DJANGO_ADMIN_USER: ${DJANGO_ADMIN_USER}
      DJANGO_ADMIN_MAIL: ${DJANGO_ADMIN_MAIL}
      DJANGO_ADMIN_PASS: ${DJANGO_ADMIN_PASS}
      APP_HOST: perktree.theedgeofrage.com
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: perktree
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      PERKS_DIR: /app/static/perks
    depends_on:
      - db

