# Generated by Django 2.1.7 on 2019-03-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perks', '0002_auto_20190324_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
